name: Deploy API server with database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API server with database
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install other dependencies
        run: sudo apt install -y curl jq build-essential

      - name: Download servant faces from Github release
        run: curl -LO $(curl -s "https://api.github.com/repos/aaanh/reroll.ing/releases" | jq -r '.[0].assets[0].browser_download_url')

      - name: Generate .env for API server
        run: